name: "build_distribution"

description: "Build and export the distribution"

runs:
  using: composite
  steps:
    - name: Collect any new commits
      shell: bash
      run: |
        git pull  # get any pushes made since the trigger began; without this job-to-job connections may fail

    - name: Set up Node.js 14
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r scripts/requirements.txt

    - name: Build distribution
      shell: bash
      run: python3 scripts/build_distribution.py

    - name: Commit changes, ready to push
      shell: bash
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add *.nt *.md *.fasta *.gb
        git diff-index --quiet HEAD . || git commit --allow-empty -m "Build distribution"

