name: generate-distribution
description: A Github action to generate a distribution from user-readable files 
runs:
    using: composite
    steps:
        - name: Set up Python 3.9
          uses: actions/setup-python@v4
          with:
            python-version: 3.9
        - name: Install dependencies
          shell: bash
          run: |
            python -m pip install --upgrade pip
            pip install -r ${{ github.action_path }}/scripts/requirements.txt

        - uses: ./.github/actions/directories_and_excel
        - uses: ./.github/actions/retrieve_parts
        - uses: ./.github/actions/build_packages
        - uses: ./.github/actions/build_distribution

author: iGEM-Engineering
branding:
    icon:  'layers'
    color: 'purple'
