name: generate-distribution
description: A Github action to generate a distribution from user-readable files 
runs:
    using: composite
    steps:
        - name: Check out this repository for building
          uses: actions/checkout@v3

        - name: Set up Python 3.9
          uses: actions/setup-python@v4
          with:
            python-version: 3.9

        - name: Set up Node.js 14
          uses: actions/setup-node@v3
          with:
            node-version: '14'

        - name: Install dependencies
          shell: bash
          run: |
            python -m pip install --upgrade pip
            pip install -r ${{ github.action_path }}/scripts/requirements.txt

        - name: Run distribution build 
          shell: bash
          run: bash ${{ github.action_path }}/entrypoint.sh


author: iGEM-Engineering
branding:
    icon:  'layers'
    color: 'purple'
