name: generate-distribution
description: A Github action to generate a distribution from user-readable files 
runs:
    using: composite
    steps:
        - name: Check out this repository for building
          uses: actions/checkout@v3

        - name: Set up Python 3.9
          uses: actions/setup-python@v4
          with:
            python-version: 3.9

        - name: Set up Node.js 14
          uses: actions/setup-node@v3
          with:
            node-version: '14'

        - name: Install dependencies
          shell: bash
          run: |
            python -m pip install --upgrade pip
            pip install -r ${{ github.action_path }}/scripts/requirements.txt

        - name: Regularize directories
          shell: bash
          run: python3 ${{ github.action_path }}/scripts/regularize_directories.py

        - name: Update CSVs
          shell: bash
          run: python3 ${{ github.action_path }}/scripts/export_csvs.py

        - name: Update SBOL
          shell: bash
          run: python3 ${{ github.action_path }}/scripts/export_sbol.py

        - name: Import parts and devices
          shell: bash
          run: python3 ${{ github.action_path }}/scripts/import_parts.py

        - name: Convert SBOL2 imports to SBOL3
          shell: bash
          run: python3 ${{ github.action_path }}/scripts/convert_sbol_2to3.py

        - name: Collate packages
          shell: bash
          run: python3 ${{ github.action_path }}/scripts/collate_packages.py

        - name: Create vector build plans
          shell: bash
          run: python3 ${{ github.action_path }}/scripts/expand_combinations.py

        - name: Generate markdown from packages
          shell: bash
          run: python3 ${{ github.action_path }}/scripts/generate_markdown.py

        - name: Build distribution
          shell: bash
          run: python3 ${{ github.action_path }}/scripts/build_distribution.py

author: iGEM-Engineering
branding:
    icon:  'layers'
    color: 'purple'
