name: generate-distribution
description: A Github action to generate a distribution from user-readable files 
runs:
    using: 'docker'
    image: 'Dockerfile'
author: iGEM-Engineering
branding:
    icon:  'layers'
    color: 'purple'
